#ifndef PORTS_HPP_
#define PORTS_HPP_

enum PortIndex {
	BLOW_MIDI_IN  = 0,
	BLOW_AUDIO_OUT = 1,
	BLOW_CONTROLLERS = 2,
	BLOW_SAMPLE = 0,
	BLOW_GAIN = 1,
	BLOW_TUNE = 2,
	BLOW_TUNE_CT = 3,
	BLOW_NR_CONTROLLERS = 4,
	BLOW_N_PORTS = BLOW_CONTROLLERS + BLOW_NR_CONTROLLERS
};

#endif /* PORTS_HPP_ */
